[project]
name = "python-anything"
version = "0.1.0"
description = "Learn Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.5.0",
    "pandas>=2.3.3",
    "pytest>=9.0.1",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
